# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Admin\Desktop\MYPROJECTS\pyqt-class-schedule\View\ui/homework.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeWorkForm(object):
    def setupUi(self, HomeWorkForm):
        HomeWorkForm.setObjectName("HomeWorkForm")
        HomeWorkForm.resize(400, 300)
        HomeWorkForm.setMinimumSize(QtCore.QSize(400, 300))
        HomeWorkForm.setMaximumSize(QtCore.QSize(400, 300))
        self.saveHWButton = QtWidgets.QPushButton(HomeWorkForm)
        self.saveHWButton.setGeometry(QtCore.QRect(300, 10, 91, 31))
        self.saveHWButton.setObjectName("saveHWButton")
        self.clearHWButton = QtWidgets.QPushButton(HomeWorkForm)
        self.clearHWButton.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.clearHWButton.setObjectName("clearHWButton")
        self.homeworkArea = QtWidgets.QPlainTextEdit(HomeWorkForm)
        self.homeworkArea.setGeometry(QtCore.QRect(10, 50, 381, 239))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.homeworkArea.setFont(font)
        self.homeworkArea.setObjectName("homeworkArea")

        self.retranslateUi(HomeWorkForm)
        QtCore.QMetaObject.connectSlotsByName(HomeWorkForm)

    def retranslateUi(self, HomeWorkForm):
        _translate = QtCore.QCoreApplication.translate
        HomeWorkForm.setWindowTitle(_translate("HomeWorkForm", "Form"))
        self.saveHWButton.setText(_translate("HomeWorkForm", "Сохранить д/з"))
        self.clearHWButton.setText(_translate("HomeWorkForm", "Очистить д/з"))
        self.homeworkArea.setPlaceholderText(_translate("HomeWorkForm", "Д/З"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeWorkForm = QtWidgets.QWidget()
    ui = Ui_HomeWorkForm()
    ui.setupUi(HomeWorkForm)
    HomeWorkForm.show()
    sys.exit(app.exec_())
